# Generated by Django 6.0.5 on 2026-05-08 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='uz', max_length=10)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('open_library', 'Open Library'), ('google_books', 'Google Books'), ('community', 'Community'), ('seed', 'Seed')], default='community', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'books',
                'indexes': [models.Index(fields=['isbn'], name='books_isbn_ce4a1a_idx'), models.Index(fields=['title'], name='books_title_7a737c_idx')],
            },
        ),
    ]
