# Generated by Django 6.0.5 on 2026-05-09 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_bookauthor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_read', 'Want to Read'), ('reading', 'Reading'), ('finished', 'Finished'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='want_to_read', max_length=20)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_books',
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_read', models.PositiveIntegerField()),
                ('page_after', models.PositiveIntegerField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='shelf.userbook')),
            ],
            options={
                'db_table': 'reading_sessions',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'status'], name='user_books_user_id_a5ff96_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['book'], name='user_books_book_id_44ba25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'book')},
        ),
    ]
