# Generated by Django 6.0.5 on 2026-05-09 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_bookauthor'),
        ('reviews', '0001_initial'),
        ('shelf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('added_book', 'Added book to shelf'), ('started_reading', 'Started reading'), ('finished_book', 'Finished book'), ('updated_progress', 'Updated progress'), ('wrote_review', 'Wrote review')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_events', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.review')),
                ('user_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelf.userbook')),
            ],
            options={
                'db_table': 'feed_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('reading_too', "I'm reading this too"), ('liked', 'Liked'), ('inspired', 'Inspired me')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='feed.feedevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reactions',
            },
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['actor', 'created_at'], name='feed_events_actor_i_6e2162_idx'),
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['created_at'], name='feed_events_created_8fa5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['event'], name='reactions_event_i_83f1a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('event', 'user')},
        ),
    ]
